version: '3.8'

services:
  coursework:
    image: course:latest
    depends_on:
      - roach
    build:
      context: .
    container_name: coursework
    hostname: roach-single
    networks:
      - roachnet
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
  roach:
    container_name: roach-single-course
    image: cockroachdb/cockroach:v23.1.11
    hostname: roach-single
    networks:
      - roachnet
    ports:
      - "26257:26257"
      - "8090:8080"
    volumes:
      - roach-single:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  roach-single:

networks:
  roachnet:
    driver: bridge