services:
  coursework:
    container_name: coursework_app
    image: coursework:latest
    ports:
      - "8080:8080"
    build: .
    # networks:
    #   - taxi-app-network
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=host=postgres_db user=yan password=3418abcd database=courseworkdb port=5432
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - ACCESS_TOKEN_SECRET_KEY=secret
      - ACCESS_TOKEN_TTL=15
      - REFRESH_TOKEN_INITIAL_LEN=32
      - REFRESH_TOKEN_TTL=60
    depends_on:
      - postgres_db
    links:
      - postgres_db
  postgres_db:
    container_name: coursework_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 3418abcd
      POSTGRES_USER: yan
      POSTGRES_DB: courseworkrdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - taxi-app-network
  redis:
    image: redis
    container_name: courseworkredis
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
